stages:
  - test

test:
  stage: test
  image: maven:3.9.6-eclipse-temurin-17

  script:
    - mvn test

  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/*.xml
    paths:
      - target/surefire-reports
